avoid-breaking-exported-api = true
warn-on-all-wildcard-imports = false
msrv = "1.70"
too-many-arguments-threshold = 10
type-complexity-threshold = 500
single-char-binding-names-threshold = 4
too-large-for-stack = 200
enum-variant-name-threshold = 3
verbose-bit-mask-threshold = 1
literal-representation-threshold = 16384
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256