#[derive(Debug, Clone)]
pub struct CommandKnowledge {
    pub name: &'static str,
    pub description: &'static str,
    pub category: &'static str,
    pub parameters: &'static [&'static str],
    pub high_risk: bool,
    pub usage_notes: &'static [&'static str],
    pub sdk_refs: &'static [&'static str],
}

#[derive(Debug, Clone)]
pub struct CommandKnowledgeBase {
    commands: Vec<CommandKnowledge>,
}

impl CommandKnowledgeBase {
    pub fn new() -> Self {
        Self {
            commands: build_command_catalog(),
        }
    }

    pub fn get_command(&self, name: &str) -> Option<&CommandKnowledge> {
        self.commands.iter().find(|c| c.name == name)
    }

    pub fn get_commands_by_category(&self, category: &str) -> Vec<&CommandKnowledge> {
        self.commands
            .iter()
            .filter(|c| c.category == category)
            .collect()
    }

    pub fn get_all_commands(&self) -> &[CommandKnowledge] {
        &self.commands
    }

    pub fn find_commands_for_purpose(&self, purpose: &str) -> Vec<&CommandKnowledge> {
        let lower = purpose.to_lowercase();
        self.commands
            .iter()
            .filter(|c| {
                c.name.to_lowercase().contains(&lower)
                    || c.description.to_lowercase().contains(&lower)
                    || c.category.to_lowercase().contains(&lower)
                    || c.usage_notes
                        .iter()
                        .any(|n| n.to_lowercase().contains(&lower))
            })
            .collect()
    }

    pub fn get_scene_workflow_commands(&self) -> Vec<&CommandKnowledge> {
        let scene_flow: &[&str] = &[
            "add_figure",
            "load_asset",
            "add_node",
            "set_light",
            "set_camera",
            "set_morph",
            "apply_pose",
            "apply_expression",
            "set_material_property",
            "set_body_opacity",
            "set_surface_opacity",
            "show_anatomy",
            "place_asset_inside",
            "set_material_texture",
            "set_render_options",
            "render_preview",
        ];
        scene_flow
            .iter()
            .filter_map(|name| self.get_command(name))
            .collect()
    }

    pub fn build_command_catalog_prompt(&self) -> String {
        let mut prompt = String::from("Available Daz Bridge commands:\n");
        for cmd in &self.commands {
            let risk = if cmd.high_risk { " [HIGH RISK]" } else { "" };
            prompt.push_str(&format!(
                "\n- {} ({}){}. {}",
                cmd.name, cmd.category, risk, cmd.description
            ));
            prompt.push_str(&format!("\n  params: {}", cmd.parameters.join(", ")));
            if !cmd.usage_notes.is_empty() {
                prompt.push_str(&format!("\n  notes: {}", cmd.usage_notes.join("; ")));
            }
        }
        prompt
    }
}

fn build_command_catalog() -> Vec<CommandKnowledge> {
    vec![
        CommandKnowledge {
            name: "get_commands",
            description: "List supported Daz bridge commands",
            category: "System",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Use to discover available commands at runtime"],
            sdk_refs: &[],
        },
        CommandKnowledge {
            name: "get_scene_info",
            description: "Get current Daz scene summary",
            category: "Scene",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Call first to understand the current scene state before planning"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "list_nodes",
            description: "List all scene nodes with their IDs and types",
            category: "Scene",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Returns node hierarchy including figures, lights, cameras, props"],
            sdk_refs: &["DzNode", "DzScene"],
        },
        CommandKnowledge {
            name: "add_node",
            description: "Add a primitive node (point_light, spot_light, distant_light, camera, null)",
            category: "Scene",
            parameters: &["type", "name"],
            high_risk: false,
            usage_notes: &[
                "Use for creating lights and cameras from scratch",
                "For figures use add_figure instead",
                "Light types: point_light, spot_light, distant_light, ambient_light",
            ],
            sdk_refs: &["DzLight", "DzCamera", "DzNull"],
        },
        CommandKnowledge {
            name: "delete_node",
            description: "Delete a node from the scene",
            category: "Scene",
            parameters: &["node_id"],
            high_risk: true,
            usage_notes: &["Cannot be undone. Use with caution."],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "get_selected_nodes",
            description: "List currently selected scene nodes",
            category: "Selection",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Use to see what the user has selected before acting on selection"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "select_node",
            description: "Select a Daz scene node by id or name",
            category: "Selection",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Use before commands that operate on 'selected' node"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "get_cameras",
            description: "List all scene cameras",
            category: "Camera",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Use to find camera names before calling set_camera"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "set_camera",
            description: "Set active camera or adjust camera properties (focal length/distance)",
            category: "Camera",
            parameters: &["camera", "focal_length", "focal_distance"],
            high_risk: false,
            usage_notes: &[
                "Switch camera by name (e.g. 'Perspective View')",
                "Omit focal params to leave them unchanged",
                "focal_length: 35mm (wide) to 200mm (tele), typical portrait: 85mm",
                "focal_distance: distance to focal plane in scene units",
            ],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "load_asset",
            description: "Load a Daz asset file into the current scene",
            category: "Assets",
            parameters: &["path"],
            high_risk: false,
            usage_notes: &[
                "Path can be relative to content directory or absolute",
                "Use search_content to find assets before loading",
                "Supports .duf, .dsf, .pz2, .bmp, etc.",
            ],
            sdk_refs: &["DzContentMgr", "DzAsset"],
        },
        CommandKnowledge {
            name: "search_content",
            description: "Search Daz content library for assets by name/type",
            category: "Assets",
            parameters: &["query", "type", "max_results"],
            high_risk: false,
            usage_notes: &[
                "Use before load_asset to find exact paths",
                "type: figure, clothing, hair, pose, material, prop, environment",
                "max_results: default 10, max 100",
            ],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "add_figure",
            description: "Add a Genesis figure (8 or 9) to the scene",
            category: "Scene",
            parameters: &["figure_type"],
            high_risk: false,
            usage_notes: &[
                "figure_type: 'genesis8' or 'genesis9'",
                "Creates a base figure with no morphs applied",
                "Use set_morph or apply_morph to customize appearance",
            ],
            sdk_refs: &["DzFigure"],
        },
        CommandKnowledge {
            name: "apply_pose",
            description: "Apply a pose file to a figure",
            category: "Pose",
            parameters: &["pose_path", "figure_id"],
            high_risk: false,
            usage_notes: &[
                "pose_path: path to .duf pose file",
                "figure_id: optional, applies to selected if omitted",
                "Use search_content to find poses first",
            ],
            sdk_refs: &["DzPose"],
        },
        CommandKnowledge {
            name: "set_morph",
            description: "Set a morph dial value on a figure (0.0–1.0)",
            category: "Properties",
            parameters: &["node_id", "morph", "value"],
            high_risk: false,
            usage_notes: &[
                "node_id: the figure node",
                "morph: exact morph dial name (e.g. 'Head_Height')",
                "value: 0.0 (minimum) to 1.0 (maximum)",
                "Use get_figure_morphs to list available morphs",
            ],
            sdk_refs: &["DzModifier", "DzFigure"],
        },
        CommandKnowledge {
            name: "get_figure_morphs",
            description: "Get all morph dials and their values for a figure",
            category: "Properties",
            parameters: &["figure_id"],
            high_risk: false,
            usage_notes: &["Use to discover available morphs before calling set_morph or apply_morph"],
            sdk_refs: &["DzModifier", "DzFigure"],
        },
        CommandKnowledge {
            name: "apply_morph",
            description: "Set a morph dial value on a figure (0.0–1.0)",
            category: "Properties",
            parameters: &["figure_id", "morph_id", "value"],
            high_risk: false,
            usage_notes: &[
                "Alternative to set_morph with different parameter format",
                "figure_id: the figure identifier",
                "morph_id: the morph identifier from get_figure_morphs",
            ],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "apply_expression",
            description: "Set an expression dial value on a figure",
            category: "Properties",
            parameters: &["figure_id", "expression_id", "value"],
            high_risk: false,
            usage_notes: &[
                "expression_id: expression name from get_active_expressions",
                "value: 0.0 to 1.0",
                "Use get_active_expressions to list available expressions",
            ],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "get_active_expressions",
            description: "Get all active expression dial values on a figure",
            category: "Properties",
            parameters: &["figure_id"],
            high_risk: false,
            usage_notes: &["Use before apply_expression to see current expression state"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "set_property",
            description: "Set a node property (transforms, visibility, etc.)",
            category: "Properties",
            parameters: &["node_id", "property", "value"],
            high_risk: false,
            usage_notes: &[
                "For morphs use set_morph instead",
                "For materials use set_material_property instead",
                "Common properties: xpos, ypos, zpos, xrot, yrot, zrot, xscale, yscale, zscale",
            ],
            sdk_refs: &["DzProperty"],
        },
        CommandKnowledge {
            name: "get_node_properties",
            description: "Get animatable properties of a node",
            category: "Properties",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &[
                "Returns list of animatable properties with their current values",
                "Use before set_property or set_keyframe to discover available properties",
            ],
            sdk_refs: &["DzProperty"],
        },
        CommandKnowledge {
            name: "set_light",
            description: "Set a light property (intensity, color, etc.)",
            category: "Lighting",
            parameters: &["node_id", "property", "value"],
            high_risk: false,
            usage_notes: &[
                "node_id: the light node (created via add_node)",
                "property: 'intensity', 'color', 'enable', 'shadow'",
                "value: for color use 'R,G,B' format (0-255), for intensity use float",
                "Create lights first with add_node, then configure with set_light",
            ],
            sdk_refs: &["DzLight"],
        },
        CommandKnowledge {
            name: "set_material_property",
            description: "Set a material property (color, roughness, etc.)",
            category: "Materials",
            parameters: &["node_id", "property", "value"],
            high_risk: false,
            usage_notes: &[
                "Common properties: 'Base Color', 'Roughness', 'Metallic', 'Opacity'",
                "For textures use set_material_texture",
            ],
            sdk_refs: &["DzMaterial"],
        },
        CommandKnowledge {
            name: "set_body_opacity",
            description: "Set opacity across all material surfaces on a figure or selected node",
            category: "Materials",
            parameters: &["node_id", "value"],
            high_risk: false,
            usage_notes: &[
                "value: opacity from 0.0 (transparent) to 1.0 (opaque); out-of-range values are clamped by the bridge",
                "Use for ghost, fade, and see-through body effects",
            ],
            sdk_refs: &["DzMaterial", "DzFloatProperty"],
        },
        CommandKnowledge {
            name: "set_surface_opacity",
            description: "Set opacity for material surfaces matching a name or pattern",
            category: "Materials",
            parameters: &["node_id", "surface_pattern", "value"],
            high_risk: false,
            usage_notes: &[
                "surface_pattern: exact or case-insensitive substring match against material name/label",
                "Use get_material_zones first if the surface name is unknown",
            ],
            sdk_refs: &["DzMaterial", "DzFloatProperty"],
        },
        CommandKnowledge {
            name: "get_internal_surfaces",
            description: "List material surfaces that look like internal anatomy or skeleton surfaces",
            category: "Materials",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &[
                "Heuristic match for names like skull, bone, rib, spine, pelvis, clavicle, scapula, skeleton",
                "Use before show_anatomy when the user wants to inspect anatomy surfaces",
            ],
            sdk_refs: &["DzMaterial"],
        },
        CommandKnowledge {
            name: "show_anatomy",
            description: "Make internal anatomy surfaces fully opaque on a figure or selected node",
            category: "Materials",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &[
                "Uses the same internal surface heuristic as get_internal_surfaces",
                "Useful after making the body transparent with set_body_opacity",
            ],
            sdk_refs: &["DzMaterial", "DzFloatProperty"],
        },
        CommandKnowledge {
            name: "place_asset_inside",
            description: "Load an asset and place it inside a figure near the torso",
            category: "Assets",
            parameters: &["figure_id", "asset_path"],
            high_risk: false,
            usage_notes: &[
                "Loads asset_path, moves the loaded node to the figure torso center, and parents it to the figure",
                "Use with opacity tools for internal placement and x-ray style workflows",
            ],
            sdk_refs: &["DzContentMgr", "DzNode", "DzBox3"],
        },
        CommandKnowledge {
            name: "get_material_properties",
            description: "Get material properties of a node (shader parameters)",
            category: "Materials",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Use before set_material_property to see current material state"],
            sdk_refs: &["DzMaterial"],
        },
        CommandKnowledge {
            name: "get_material_zones",
            description: "Get material zone names on a figure",
            category: "Materials",
            parameters: &["figure_id"],
            high_risk: false,
            usage_notes: &["Use to discover surface zones before setting material properties per zone"],
            sdk_refs: &["DzMaterial"],
        },
        CommandKnowledge {
            name: "set_material_texture",
            description: "Assign a texture map file to a material surface channel",
            category: "Materials",
            parameters: &["node_id", "channel", "file_path"],
            high_risk: false,
            usage_notes: &[
                "channel: 'Base Color', 'Roughness', 'Normal', 'Metallic', 'Opacity', 'Subsurface'",
                "file_path: absolute path to texture image file",
                "Use get_material_channels to see current texture assignments",
            ],
            sdk_refs: &["DzImageProperty", "DzDefaultMaterial"],
        },
        CommandKnowledge {
            name: "get_material_channels",
            description: "Get all surface channels with texture paths and values",
            category: "Materials",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Use before set_material_texture to see current texture state"],
            sdk_refs: &["DzImageProperty", "DzDefaultMaterial"],
        },
        CommandKnowledge {
            name: "get_fitted_items",
            description: "Get all fitted clothing/accessories on a figure",
            category: "Scene",
            parameters: &["figure_id"],
            high_risk: false,
            usage_notes: &["Use to see what clothing is already fitted before adding more"],
            sdk_refs: &["DzFigure"],
        },
        CommandKnowledge {
            name: "get_scene_assets",
            description: "Get list of loaded asset labels currently in the Daz Studio scene",
            category: "Scene",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Returns asset labels for all loaded assets in the scene"],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "get_geoshells",
            description: "Get all Geometry Shells in the scene",
            category: "Scene",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Geometry shells are generated by some clothing items"],
            sdk_refs: &["DzGeoShell"],
        },
        CommandKnowledge {
            name: "get_node_transform",
            description: "Get node world-space transform (position, rotation, scale)",
            category: "Scene",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &[
                "Returns position as [x, y, z] array",
                "Returns rotation as Euler angles [x, y, z] in degrees",
                "Returns scale as [x, y, z] array",
            ],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "set_node_transform",
            description: "Set node world-space position, rotation, or scale",
            category: "Scene",
            parameters: &["node_id", "position", "rotation", "scale"],
            high_risk: true,
            usage_notes: &[
                "position: [x, y, z] float array",
                "rotation: [x, y, z] float array in degrees",
                "scale: [x, y, z] float array",
                "Omit arrays you don't want to change",
            ],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "begin_undo_batch",
            description: "Start a new undo batch in Daz Studio",
            category: "Scene",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Always call before making multiple changes so user can undo as one action"],
            sdk_refs: &["DzUndoMgr"],
        },
        CommandKnowledge {
            name: "accept_undo_batch",
            description: "Accept the current undo batch with a caption",
            category: "Scene",
            parameters: &["caption"],
            high_risk: false,
            usage_notes: &["caption: human-readable description for the undo history entry"],
            sdk_refs: &["DzUndoMgr"],
        },
        CommandKnowledge {
            name: "cancel_undo_batch",
            description: "Cancel the current undo batch",
            category: "Scene",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Use to roll back changes if something goes wrong mid-batch"],
            sdk_refs: &["DzUndoMgr"],
        },
        CommandKnowledge {
            name: "save_scene",
            description: "Save the current scene to a file",
            category: "Scene",
            parameters: &["path"],
            high_risk: true,
            usage_notes: &["Overwrites existing file. Use with caution."],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "load_scene",
            description: "Load a scene file with method (default/new/merge)",
            category: "Scene",
            parameters: &["path", "method"],
            high_risk: true,
            usage_notes: &["method: 'default', 'new' (clears first), or 'merge'"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "clear_scene",
            description: "Clear the current scene",
            category: "Scene",
            parameters: &[],
            high_risk: true,
            usage_notes: &["Cannot be undone. All unsaved work will be lost."],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "render_preview",
            description: "Trigger a Daz preview render using current settings",
            category: "Render",
            parameters: &[],
            high_risk: false,
            usage_notes: &[
                "Set render options first with set_render_settings or set_render_options",
                "Renders using the active viewport camera",
            ],
            sdk_refs: &["DzRenderMgr"],
        },
        CommandKnowledge {
            name: "set_render_settings",
            description: "Apply render resolution and quality presets quickly",
            category: "Render",
            parameters: &["width", "height"],
            high_risk: false,
            usage_notes: &[
                "Quick preset-based render config",
                "For full control use set_render_options instead",
                "Common presets: 1920x1080 (HD), 3840x2160 (4K), 800x600 (preview)",
            ],
            sdk_refs: &["DzRenderMgr"],
        },
        CommandKnowledge {
            name: "set_render_options",
            description: "Set render quality, resolution, and output options in detail",
            category: "Render",
            parameters: &["width", "height", "pixel_samples", "ray_trace_depth", "shading_rate", "gamma"],
            high_risk: false,
            usage_notes: &[
                "For quick setup use set_render_settings instead",
                "pixel_samples: 16 (draft) to 4096 (final quality)",
                "ray_trace_depth: 2 (draft) to 8 (final quality, default: 4)",
                "shading_rate: 1.0 (default)",
                "gamma: 2.2 (sRGB default)",
            ],
            sdk_refs: &["DzRenderOptions", "DzRenderMgr"],
        },
        CommandKnowledge {
            name: "capture_viewport",
            description: "Capture the active Daz viewport to an image file",
            category: "Viewport",
            parameters: &["path"],
            high_risk: false,
            usage_notes: &["path: absolute path to save the PNG image"],
            sdk_refs: &["DzViewport"],
        },
        CommandKnowledge {
            name: "set_viewport_mode",
            description: "Set viewport display mode (texture, shaded, wireframe, etc.)",
            category: "Viewport",
            parameters: &["mode"],
            high_risk: false,
            usage_notes: &[
                "mode: 'texture' (full textured), 'shaded' (smooth), 'wireframe', 'lit_wireframe', 'smooth_flat'",
                "Useful for preview performance vs quality control",
            ],
            sdk_refs: &["DzViewport"],
        },
        CommandKnowledge {
            name: "viewport_click",
            description: "Pick and select a node in the viewport at given coordinates",
            category: "Viewport",
            parameters: &["x", "y"],
            high_risk: false,
            usage_notes: &["x, y: pixel coordinates in the viewport"],
            sdk_refs: &["DzViewport"],
        },
        CommandKnowledge {
            name: "set_keyframe",
            description: "Set an animatable float property keyframe at a specific frame",
            category: "Animation",
            parameters: &["node_id", "property", "frame", "value", "interpolation"],
            high_risk: false,
            usage_notes: &[
                "property: animatable property name (see get_node_properties)",
                "frame: timeline frame number",
                "interpolation: 'linear', 'bezier', 'smooth', 'step', or 'auto'",
            ],
            sdk_refs: &["DzKeyframe", "DzFloatKeyframe"],
        },
        CommandKnowledge {
            name: "set_timeline_range",
            description: "Set the Daz Studio play range and animation range",
            category: "Animation",
            parameters: &["start_frame", "end_frame"],
            high_risk: false,
            usage_notes: &["Sets both the playback range and animation range"],
            sdk_refs: &["DzTime"],
        },
        CommandKnowledge {
            name: "seek_to_frame",
            description: "Move the timeline cursor to a specific frame",
            category: "Animation",
            parameters: &["frame"],
            high_risk: false,
            usage_notes: &["Use before setting keyframes to position the timeline"],
            sdk_refs: &["DzTime"],
        },
        CommandKnowledge {
            name: "play_timeline",
            description: "Start Daz Studio timeline playback",
            category: "Animation",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Starts playback from current frame"],
            sdk_refs: &["DzTime"],
        },
        CommandKnowledge {
            name: "pause_timeline",
            description: "Pause Daz Studio timeline playback",
            category: "Animation",
            parameters: &[],
            high_risk: false,
            usage_notes: &[],
            sdk_refs: &["DzTime"],
        },
        CommandKnowledge {
            name: "stop_timeline",
            description: "Stop playback and reset to frame 0",
            category: "Animation",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Stops and resets the timeline cursor to frame 0"],
            sdk_refs: &["DzTime"],
        },
        CommandKnowledge {
            name: "get_timeline_state",
            description: "Query current timeline frame, range, fps, and playback state",
            category: "Animation",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Returns current frame, start/end range, FPS, and whether playing"],
            sdk_refs: &["DzTime"],
        },
        CommandKnowledge {
            name: "list_bones",
            description: "List all bones in a figure's skeleton",
            category: "Animation",
            parameters: &["figure_id"],
            high_risk: false,
            usage_notes: &[
                "Returns hierarchical bone names (e.g. 'hip', 'abdomen', 'chest', 'lShldr', 'rShldr', 'neck', 'head')",
                "Use before set_bone_transform to discover bone names",
            ],
            sdk_refs: &["DzBone", "DzSkeleton"],
        },
        CommandKnowledge {
            name: "set_bone_transform",
            description: "Set a bone's world-space position or rotation",
            category: "Animation",
            parameters: &["figure_id", "bone_name", "position", "rotation"],
            high_risk: true,
            usage_notes: &[
                "bone_name: from list_bones output",
                "position: [x, y, z] or omit",
                "rotation: [x, y, z] Euler angles in degrees or omit",
                "Can break figure posing if used incorrectly",
            ],
            sdk_refs: &["DzBone", "DzSkeleton"],
        },
        CommandKnowledge {
            name: "list_keyframes",
            description: "List all keyframes on a node property",
            category: "Animation",
            parameters: &["node_id", "property"],
            high_risk: false,
            usage_notes: &["Use to inspect existing animation data before modifying keyframes"],
            sdk_refs: &["DzKeyframe"],
        },
        CommandKnowledge {
            name: "delete_keyframes",
            description: "Delete keyframes from a node property (range or all)",
            category: "Animation",
            parameters: &["node_id", "property", "start", "end"],
            high_risk: true,
            usage_notes: &["Omitting start/end deletes all keyframes on that property"],
            sdk_refs: &["DzKeyframe"],
        },
        CommandKnowledge {
            name: "run_dforce_simulation",
            description: "Run a dForce physics simulation via inline DazScript",
            category: "Animation",
            parameters: &["node_id", "start_frame", "end_frame"],
            high_risk: false,
            usage_notes: &[
                "Simulates dynamic clothing/hair physics",
                "Requires dForce-enabled clothing to be fitted to figure",
                "start_frame/end_frame: frame range for simulation",
            ],
            sdk_refs: &["DzSimulator"],
        },
        CommandKnowledge {
            name: "run_script",
            description: "Evaluate arbitrary DazScript on the main thread",
            category: "Scripting",
            parameters: &["script", "args"],
            high_risk: true,
            usage_notes: &[
                "Can execute any DazScript API call",
                "Use as last resort when no bridge command exists for a task",
                "script: DazScript code as a string",
            ],
            sdk_refs: &["DazScript"],
        },
        CommandKnowledge {
            name: "import_model",
            description: "Import a model file through Daz (OBJ, FBX, etc.)",
            category: "Assets",
            parameters: &["path", "settings"],
            high_risk: false,
            usage_notes: &[
                "Supported formats: OBJ, FBX, glTF",
                "settings: JSON object with import options",
            ],
            sdk_refs: &["DzImportMgr"],
        },
        CommandKnowledge {
            name: "export_scene",
            description: "Export scene or node through Daz",
            category: "Assets",
            parameters: &["node_id", "path", "settings"],
            high_risk: true,
            usage_notes: &["node_id: empty for full scene, specific node for single export"],
            sdk_refs: &["DzExportMgr", "DzExporter"],
        },
        CommandKnowledge {
            name: "apply_phy_modifier",
            description: "Apply DazPilot physics modifier to a node (cloth/jelly/hair)",
            category: "Physics",
            parameters: &["node_id", "stiffness", "damping", "mass"],
            high_risk: false,
            usage_notes: &[
                "stiffness: 0.0 (floppy) to 1.0 (rigid)",
                "damping: 0.0 to 1.0 (energy dissipation)",
                "mass: > 0.0 (heavier = more gravity influence)",
            ],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "remove_phy_modifier",
            description: "Remove DazPilot physics modifier from a node",
            category: "Physics",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Removes the DazPilot physics modifier if present"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "set_phy_modifier_params",
            description: "Update DazPilot physics modifier parameters",
            category: "Physics",
            parameters: &["node_id", "stiffness", "damping", "mass"],
            high_risk: false,
            usage_notes: &["Updates existing modifier without reapplying"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "get_bounding_boxes",
            description: "Get world-space 3D bounding boxes of all scene nodes",
            category: "Vision",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Returns center, size, and min/max for each node's bounding box"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "list_modifiers",
            description: "List all modifiers on a node's geometry object",
            category: "Scene",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &[
                "Returns modifier names and types for the given node",
                "Useful for inspecting figure morphs, smoothing, subdivision modifiers",
            ],
            sdk_refs: &["DzModifier"],
        },
        // ── Environment Commands ───────────────────────────────────────────────
        CommandKnowledge {
            name: "set_environment",
            description: "Set environment map or preset",
            category: "Environment",
            parameters: &["type", "preset", "intensity", "rotation"],
            high_risk: false,
            usage_notes: &["type: hdri, color, preset, gradient", "Use clear_environment to remove environment elements"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "add_ground",
            description: "Add a ground plane to the scene",
            category: "Environment",
            parameters: &["type", "color", "size"],
            high_risk: false,
            usage_notes: &["type: plane, grid, reflective", "Creates a ground plane under the scene"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_fog",
            description: "Enable/configure fog in the scene",
            category: "Environment",
            parameters: &["enabled", "density", "color", "distance"],
            high_risk: false,
            usage_notes: &["enabled: true/false to toggle", "density: 0.0 to 1.0"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_sun",
            description: "Set sun position and color",
            category: "Environment",
            parameters: &["direction", "intensity", "color"],
            high_risk: false,
            usage_notes: &["direction: [x, y, z] array for sun direction", "intensity: 0.0 to 10.0"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_time_of_day",
            description: "Set scene time of day with automatic lighting",
            category: "Environment",
            parameters: &["time", "adjust_env"],
            high_risk: false,
            usage_notes: &["time: 0.0 (dawn) to 24.0 (night)", "adjust_env: auto-adjust environment"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "add_env_light",
            description: "Add an environment fill/rim/bounce light",
            category: "Lighting",
            parameters: &["type", "intensity", "color", "direction"],
            high_risk: false,
            usage_notes: &["type: fill, rim, bounce", "Creates an additional environment light"],
            sdk_refs: &["DzLight"],
        },
        CommandKnowledge {
            name: "rotate_environment",
            description: "Rotate the environment map",
            category: "Environment",
            parameters: &["rotation", "hdri_only"],
            high_risk: false,
            usage_notes: &["Rotation in degrees", "hdri_only: only rotate HDRI if true"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "get_environment_info",
            description: "Get current environment settings",
            category: "Environment",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Returns current environment state"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "clear_environment",
            description: "Remove environment elements (hdri/ground/fog)",
            category: "Environment",
            parameters: &["hdri", "ground", "fog"],
            high_risk: false,
            usage_notes: &["Selectively remove HDRI, ground, or fog"],
            sdk_refs: &["DzScript"],
        },
        // ── Figure Commands ────────────────────────────────────────────────────
        CommandKnowledge {
            name: "apply_figure_preset",
            description: "Apply a figure/character preset",
            category: "Figure",
            parameters: &["figure_id", "preset_path", "apply_morphs", "apply_materials"],
            high_risk: false,
            usage_notes: &["applies a full character preset (morphs+materials)"],
            sdk_refs: &["DzFigure"],
        },
        CommandKnowledge {
            name: "list_figures",
            description: "List all figure nodes in the scene",
            category: "Figure",
            parameters: &["include_details"],
            high_risk: false,
            usage_notes: &["include_details: true for extended info"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "remove_figure",
            description: "Remove a figure from the scene",
            category: "Figure",
            parameters: &["figure_id"],
            high_risk: true,
            usage_notes: &["Removes figure and all children from scene"],
            sdk_refs: &["DzScene"],
        },
        // ── Selection Commands ──────────────────────────────────────────────────
        CommandKnowledge {
            name: "select_by_type",
            description: "Select nodes by type and optional name filter",
            category: "Selection",
            parameters: &["type", "mode", "name_contains"],
            high_risk: false,
            usage_notes: &["type: figure, light, camera, prop, bone", "mode: replace, add, remove"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "select_hierarchy",
            description: "Select a node hierarchy",
            category: "Selection",
            parameters: &["node_id", "include_parent"],
            high_risk: false,
            usage_notes: &["include_parent: include parent node in selection"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "invert_selection",
            description: "Invert the current node selection",
            category: "Selection",
            parameters: &["type"],
            high_risk: false,
            usage_notes: &["type: optional filter by node type"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "save_selection",
            description: "Save current selection set",
            category: "Selection",
            parameters: &["name"],
            high_risk: false,
            usage_notes: &["Saves current selection as a named set"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "load_selection",
            description: "Load a saved selection set",
            category: "Selection",
            parameters: &["name"],
            high_risk: false,
            usage_notes: &["Restores a previously saved selection set"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "select_all",
            description: "Select all nodes in the scene",
            category: "Selection",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Select all nodes in the scene"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "deselect_all",
            description: "Deselect all nodes",
            category: "Selection",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Deselect all currently selected nodes"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "select_children",
            description: "Select all children of a node",
            category: "Selection",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Select all children of a specified node"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "select_parent",
            description: "Select the parent of the current selection",
            category: "Selection",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Select parent of the current selection"],
            sdk_refs: &["DzSelectionMgr"],
        },
        CommandKnowledge {
            name: "get_selection_count",
            description: "Get the number of selected nodes",
            category: "Selection",
            parameters: &[],
            high_risk: false,
            usage_notes: &["Returns number of selected nodes"],
            sdk_refs: &["DzSelectionMgr"],
        },
        // ── Camera Commands ─────────────────────────────────────────────────────
        CommandKnowledge {
            name: "create_camera",
            description: "Create a new camera node",
            category: "Camera",
            parameters: &["name", "position", "focal_length"],
            high_risk: false,
            usage_notes: &["Creates a new camera at position looking at origin"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "set_camera_transform",
            description: "Position and orient a camera",
            category: "Camera",
            parameters: &["camera_id", "position", "target"],
            high_risk: false,
            usage_notes: &["position: [x, y, z]", "target: [x, y, z] look-at point"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "set_focal_length",
            description: "Set camera focal length in mm",
            category: "Camera",
            parameters: &["camera_id", "focal_length"],
            high_risk: false,
            usage_notes: &["focal_length: in mm (35-200, typical portrait 85)"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "set_aperture",
            description: "Set camera aperture and depth of field",
            category: "Camera",
            parameters: &["camera_id", "f_stop", "enable_dof", "focus_distance"],
            high_risk: false,
            usage_notes: &["f_stop: lower = more blur", "enable_dof: toggle depth of field"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "focus_camera",
            description: "Point camera to look at a target node",
            category: "Camera",
            parameters: &["camera_id", "target", "offset"],
            high_risk: false,
            usage_notes: &["Target: node ID to focus on", "offset: optional positional offset"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "delete_camera",
            description: "Delete a camera from the scene",
            category: "Camera",
            parameters: &["camera_name"],
            high_risk: false,
            usage_notes: &["Remove a camera by name"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "set_camera_target",
            description: "Set camera aim/focus point",
            category: "Camera",
            parameters: &["camera_name", "target"],
            high_risk: false,
            usage_notes: &["Set camera aim point"],
            sdk_refs: &["DzCamera"],
        },
        CommandKnowledge {
            name: "get_camera_properties",
            description: "Get detailed properties of a camera",
            category: "Camera",
            parameters: &["camera_name"],
            high_risk: false,
            usage_notes: &["Get detailed camera properties"],
            sdk_refs: &["DzCamera"],
        },
        // ── Viewport Commands ───────────────────────────────────────────────────
        CommandKnowledge {
            name: "set_display_mode",
            description: "Set viewport display mode (textured, solid, wireframe, etc.)",
            category: "Viewport",
            parameters: &["mode", "viewport"],
            high_risk: false,
            usage_notes: &["mode: textured, solid, wireframe, shaded"],
            sdk_refs: &["Dz3DViewport"],
        },
        CommandKnowledge {
            name: "set_viewport_quality",
            description: "Set viewport rendering quality",
            category: "Viewport",
            parameters: &["quality", "texture_resolution", "anti_aliasing"],
            high_risk: false,
            usage_notes: &["quality: low, medium, high, ultra"],
            sdk_refs: &["Dz3DViewport"],
        },
        CommandKnowledge {
            name: "toggle_guide",
            description: "Show/hide a viewport guide element",
            category: "Viewport",
            parameters: &["guide", "show"],
            high_risk: false,
            usage_notes: &["guide: grid, origin, ground, horizon"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_viewport_camera",
            description: "Set active viewport camera",
            category: "Viewport",
            parameters: &["camera", "viewport"],
            high_risk: false,
            usage_notes: &["Switch viewport to a specific camera"],
            sdk_refs: &["Dz3DViewport"],
        },
        CommandKnowledge {
            name: "set_viewport_lighting",
            description: "Set viewport lighting mode",
            category: "Viewport",
            parameters: &["lighting", "ambient_intensity"],
            high_risk: false,
            usage_notes: &["lighting: default, ambient_only, headlamp, scene"],
            sdk_refs: &["Dz3DViewport"],
        },
        CommandKnowledge {
            name: "center_view",
            description: "Center viewport on a node",
            category: "Viewport",
            parameters: &["node_id", "animate"],
            high_risk: false,
            usage_notes: &["node_id: center on this node", "animate: smooth transition"],
            sdk_refs: &["Dz3DViewport"],
        },
        // ── Render Commands ─────────────────────────────────────────────────────
        CommandKnowledge {
            name: "render",
            description: "Render preview, region, or final output",
            category: "Render",
            parameters: &["quality", "width", "height", "mode"],
            high_risk: false,
            usage_notes: &["quality: draft, preview, final", "mode: full, region"],
            sdk_refs: &["DzRenderMgr"],
        },
        CommandKnowledge {
            name: "set_render_output",
            description: "Configure render output format and path",
            category: "Render",
            parameters: &["format", "path", "filename", "include_alpha"],
            high_risk: false,
            usage_notes: &["format: png, jpg, tif, bmp, exr", "include_alpha: transparency"],
            sdk_refs: &["DzRenderOptions"],
        },
        CommandKnowledge {
            name: "set_render_engine",
            description: "Select render engine and GPU options",
            category: "Render",
            parameters: &["engine", "use_gpu", "gpu_devices"],
            high_risk: false,
            usage_notes: &["engine: iray, nvlink, renderman, octane", "use_gpu: toggle GPU rendering"],
            sdk_refs: &["DzRenderOptions"],
        },
        CommandKnowledge {
            name: "set_resolution",
            description: "Set render output resolution",
            category: "Render",
            parameters: &["width", "height"],
            high_risk: false,
            usage_notes: &["Sets render resolution width x height"],
            sdk_refs: &["DzRenderOptions"],
        },
        CommandKnowledge {
            name: "render_region",
            description: "Render a specific viewport region",
            category: "Render",
            parameters: &["x", "y", "width", "height", "quality"],
            high_risk: false,
            usage_notes: &["Render a specific viewport region"],
            sdk_refs: &["DzRenderMgr"],
        },
        CommandKnowledge {
            name: "queue_render",
            description: "Add a render pass to the queue",
            category: "Render",
            parameters: &["pass_name", "camera_name"],
            high_risk: false,
            usage_notes: &["Add passes to render queue for batch processing"],
            sdk_refs: &["DzRenderMgr"],
        },
        CommandKnowledge {
            name: "cancel_render",
            description: "Cancel the current render",
            category: "Render",
            parameters: &["clear_queue"],
            high_risk: false,
            usage_notes: &["clear_queue: also clear pending queue items"],
            sdk_refs: &["DzRenderMgr"],
        },
        CommandKnowledge {
            name: "set_denoising",
            description: "Configure render denoising settings",
            category: "Render",
            parameters: &["enabled", "strength", "mode"],
            high_risk: false,
            usage_notes: &["strength: 0.0 to 1.0", "mode: fast, high_quality"],
            sdk_refs: &["DzRenderOptions"],
        },
        // ── Export Commands ─────────────────────────────────────────────────────
        CommandKnowledge {
            name: "export_fbx",
            description: "Export scene to FBX format",
            category: "Export",
            parameters: &["filepath", "selected_only", "scale", "axis_system", "embed_textures", "triangulate"],
            high_risk: true,
            usage_notes: &["Exports to FBX with configurable options"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "export_obj",
            description: "Export scene to OBJ format",
            category: "Export",
            parameters: &["filepath", "selected_only", "export_materials"],
            high_risk: true,
            usage_notes: &["export_materials: include material file"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "export_gltf",
            description: "Export scene to glTF format",
            category: "Export",
            parameters: &["filepath", "selected_only", "binary", "compress", "include_animations"],
            high_risk: true,
            usage_notes: &["binary: use .glb format", "compress: apply Draco compression"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "export_collada",
            description: "Export scene to Collada DAE format",
            category: "Export",
            parameters: &["filepath", "selected_only", "export_normals", "export_uvs"],
            high_risk: true,
            usage_notes: &["Exports to Collada DAE format"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "export_usd",
            description: "Export scene to USD/USDZ format",
            category: "Export",
            parameters: &["filepath", "selected_only", "include_animations", "flatten"],
            high_risk: true,
            usage_notes: &["flatten: flatten scene hierarchy"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "export_selected",
            description: "Export selected nodes to a file",
            category: "Export",
            parameters: &["filepath", "format"],
            high_risk: true,
            usage_notes: &["Export selected nodes to given format"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "batch_export",
            description: "Batch export multiple items to files",
            category: "Export",
            parameters: &["dir", "items", "format", "name_pattern"],
            high_risk: true,
            usage_notes: &["Export multiple items to files using pattern"],
            sdk_refs: &["DzExportMgr"],
        },
        CommandKnowledge {
            name: "export_animation",
            description: "Export animation data to a file",
            category: "Export",
            parameters: &["filepath", "figure_id", "format", "bake_keyframes", "frame_rate"],
            high_risk: true,
            usage_notes: &["bake_keyframes: bake transforms to keyframes"],
            sdk_refs: &["DzExportMgr"],
        },
        // ── Pose Commands ───────────────────────────────────────────────────────
        CommandKnowledge {
            name: "list_poses",
            description: "List available pose presets",
            category: "Pose",
            parameters: &["category", "figure_type", "mood"],
            high_risk: false,
            usage_notes: &["category: optional filter", "figure_type: genesis8, genesis9"],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "save_pose",
            description: "Save current pose as a preset",
            category: "Pose",
            parameters: &["figure_id", "name", "category", "include_facial"],
            high_risk: false,
            usage_notes: &["include_facial: also save facial expressions"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "blend_poses",
            description: "Blend between two poses",
            category: "Pose",
            parameters: &["figure_id", "pose_a", "pose_b", "blend"],
            high_risk: false,
            usage_notes: &["blend: 0.0 (pose_a) to 1.0 (pose_b)"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "mirror_pose",
            description: "Mirror the current pose left-right",
            category: "Pose",
            parameters: &["figure_id", "selected_only"],
            high_risk: false,
            usage_notes: &["selected_only: only mirror selected bones"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "asymmetric_pose",
            description: "Apply different poses to left and right sides",
            category: "Pose",
            parameters: &["figure_id", "left", "right"],
            high_risk: false,
            usage_notes: &["Apply different poses to left and right body sides"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "reset_pose",
            description: "Reset a figure to T-pose or A-pose",
            category: "Pose",
            parameters: &["figure_id", "pose_type", "preserve_facial"],
            high_risk: false,
            usage_notes: &["pose_type: t_pose, a_pose", "preserve_facial: keep expression"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "random_pose",
            description: "Apply a random pose to a figure",
            category: "Pose",
            parameters: &["figure_id", "category", "intensity"],
            high_risk: false,
            usage_notes: &["intensity: 0.0 to 1.0"],
            sdk_refs: &["DzScript"],
        },
        // ── Hair Commands ───────────────────────────────────────────────────────
        CommandKnowledge {
            name: "load_hair",
            description: "Load a hair asset from the content library",
            category: "Hair",
            parameters: &["name", "figure_id", "color"],
            high_risk: false,
            usage_notes: &["Load hair from content library by name"],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "style_hair",
            description: "Apply a hair styling preset",
            category: "Hair",
            parameters: &["hair_id", "preset"],
            high_risk: false,
            usage_notes: &["Apply a styling preset to hair"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_hair_color",
            description: "Change hair color with optional highlights/roots",
            category: "Hair",
            parameters: &["hair_id", "color", "highlights", "root_color"],
            high_risk: false,
            usage_notes: &["color: hex or name", "highlights: optional highlight color"],
            sdk_refs: &["DzMaterial"],
        },
        CommandKnowledge {
            name: "apply_hair_physics",
            description: "Configure dForce physics on hair",
            category: "Hair",
            parameters: &["hair_id", "enable", "stiffness", "gravity_scale", "wind"],
            high_risk: false,
            usage_notes: &["Configure dForce physics on hair"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_hair_length",
            description: "Adjust hair length preset",
            category: "Hair",
            parameters: &["hair_id", "length", "scale_factor"],
            high_risk: false,
            usage_notes: &["Adjust hair length"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_hair_volume",
            description: "Adjust hair volume/thickness",
            category: "Hair",
            parameters: &["hair_id", "volume"],
            high_risk: false,
            usage_notes: &["Adjust hair volume/thickness"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "list_hair_presets",
            description: "List available hair presets",
            category: "Hair",
            parameters: &["figure_type"],
            high_risk: false,
            usage_notes: &["Filter by figure type"],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "remove_hair",
            description: "Remove a hair asset from the scene",
            category: "Hair",
            parameters: &["hair_id", "keep_textures"],
            high_risk: false,
            usage_notes: &["keep_textures: keep texture files loaded"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "set_hair_shader",
            description: "Change hair shader settings (glossy, matte, etc.)",
            category: "Hair",
            parameters: &["hair_id", "shader_type", "gloss", "specular"],
            high_risk: false,
            usage_notes: &["shader_type: glossy, matte, natural"],
            sdk_refs: &["DzMaterial"],
        },
        CommandKnowledge {
            name: "apply_hair_preset",
            description: "Apply a complete hair style preset",
            category: "Hair",
            parameters: &["hair_id", "preset"],
            high_risk: false,
            usage_notes: &["Apply complete hair style preset"],
            sdk_refs: &["DzScript"],
        },
        // ── Clothing/Fitting Commands ───────────────────────────────────────────
        CommandKnowledge {
            name: "load_clothing",
            description: "Load a clothing asset onto a figure",
            category: "Fitting",
            parameters: &["name", "fit_mode", "figure_id"],
            high_risk: false,
            usage_notes: &["fit_mode: auto, manual, none"],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "fit_clothing",
            description: "Fit clothing to a figure",
            category: "Fitting",
            parameters: &["clothing_id", "figure_id", "fit_type", "clear_morphs"],
            high_risk: false,
            usage_notes: &["clear_morphs: clear fitting morphs before fitting"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "remove_clothing",
            description: "Remove clothing from a figure or scene",
            category: "Fitting",
            parameters: &["clothing_id", "remove_from_scene"],
            high_risk: false,
            usage_notes: &["remove_from_scene: also remove from scene"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "list_worn_items",
            description: "List items worn by a figure",
            category: "Fitting",
            parameters: &["figure_id"],
            high_risk: false,
            usage_notes: &["List items currently worn by a figure"],
            sdk_refs: &["DzFigure"],
        },
        CommandKnowledge {
            name: "set_clothing_params",
            description: "Set a clothing parameter value",
            category: "Fitting",
            parameters: &["clothing_id", "parameter", "value"],
            high_risk: false,
            usage_notes: &["Set dynamic clothing parameters"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "suggest_outfit",
            description: "Suggest an outfit for a figure",
            category: "Fitting",
            parameters: &["figure_id", "style"],
            high_risk: false,
            usage_notes: &["style: casual, formal, fantasy, etc."],
            sdk_refs: &["DzContentMgr"],
        },
        // ── Props Commands ──────────────────────────────────────────────────────
        CommandKnowledge {
            name: "load_prop",
            description: "Load a prop from the content library",
            category: "Props",
            parameters: &["name", "category", "position"],
            high_risk: false,
            usage_notes: &["Load a prop from the content library"],
            sdk_refs: &["DzContentMgr"],
        },
        CommandKnowledge {
            name: "position_prop",
            description: "Position a prop in the scene",
            category: "Props",
            parameters: &["prop_id", "position", "relative"],
            high_risk: false,
            usage_notes: &["relative: position relative to current"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "rotate_prop",
            description: "Rotate a prop",
            category: "Props",
            parameters: &["prop_id", "rotation", "relative"],
            high_risk: false,
            usage_notes: &["relative: rotate relative to current"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "scale_prop",
            description: "Scale a prop uniformly or per-axis",
            category: "Props",
            parameters: &["prop_id", "scale", "relative"],
            high_risk: false,
            usage_notes: &["scale: uniform or per-axis [x, y, z]"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "list_props",
            description: "List props in the scene",
            category: "Props",
            parameters: &["category"],
            high_risk: false,
            usage_notes: &["category: optional filter by category"],
            sdk_refs: &["DzScene"],
        },
        // ── Morph Commands ──────────────────────────────────────────────────────
        CommandKnowledge {
            name: "batch_set_morphs",
            description: "Set multiple morph values at once",
            category: "Morphs",
            parameters: &["figure_id", "morphs"],
            high_risk: false,
            usage_notes: &["morphs: JSON object of morph_name: value pairs"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "symmetry_morphs",
            description: "Mirror morph values symmetrically left-right",
            category: "Morphs",
            parameters: &["figure_id", "direction", "morph_group"],
            high_risk: false,
            usage_notes: &["direction: left_to_right, right_to_left, symmetrical"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "randomize_morphs",
            description: "Randomize morph values on a figure",
            category: "Morphs",
            parameters: &["figure_id", "intensity", "morph_group"],
            high_risk: false,
            usage_notes: &["intensity: 0.0 to 1.0"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "save_morph_preset",
            description: "Save current morph values as a preset",
            category: "Morphs",
            parameters: &["figure_id", "preset_name", "morph_group"],
            high_risk: false,
            usage_notes: &["Saves morph values as a reusable preset"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "load_morph_preset",
            description: "Load a morph preset onto a figure",
            category: "Morphs",
            parameters: &["figure_id", "preset_name", "blend"],
            high_risk: false,
            usage_notes: &["blend: 0.0 to 1.0 blend strength"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "reset_morphs",
            description: "Reset all morphs on a figure to zero",
            category: "Morphs",
            parameters: &["figure_id", "morph_group"],
            high_risk: false,
            usage_notes: &["morph_group: optional category filter"],
            sdk_refs: &["DzModifier"],
        },
        // ── Physics Commands ────────────────────────────────────────────────────
        CommandKnowledge {
            name: "simulate_physics",
            description: "Run a physics simulation on nodes",
            category: "Physics",
            parameters: &["node_ids", "frames", "start_frame", "real_time"],
            high_risk: false,
            usage_notes: &["Run physics simulation on specified nodes"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_wind",
            description: "Set wind parameters for physics simulation",
            category: "Physics",
            parameters: &["direction", "speed", "turbulence", "gust_strength"],
            high_risk: false,
            usage_notes: &["Set wind direction, speed, and turbulence"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_gravity",
            description: "Set gravity for physics simulation",
            category: "Physics",
            parameters: &["strength", "direction", "node_id"],
            high_risk: false,
            usage_notes: &["strength: multiplier, default 1.0"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "add_collision",
            description: "Add a collision object for physics",
            category: "Physics",
            parameters: &["node_id", "shape", "friction"],
            high_risk: false,
            usage_notes: &["shape: sphere, box, capsule, mesh"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "set_physics_props",
            description: "Set physics properties on a node (mass, stiffness, etc.)",
            category: "Physics",
            parameters: &["node_id", "mass", "stiffness", "damping", "collision"],
            high_risk: false,
            usage_notes: &["Set mass, stiffness, damping, collision on a node"],
            sdk_refs: &["DzModifier"],
        },
        CommandKnowledge {
            name: "remove_physics",
            description: "Remove physics modifiers from a node",
            category: "Physics",
            parameters: &["node_id", "remove_modifiers"],
            high_risk: false,
            usage_notes: &["remove_modifiers: clean up all physics modifiers"],
            sdk_refs: &["DzModifier"],
        },
        // ── Rigging Commands ────────────────────────────────────────────────────
        CommandKnowledge {
            name: "get_joint_list",
            description: "List all joints/bones in a figure",
            category: "Rigging",
            parameters: &["figure_id", "include_hidden"],
            high_risk: false,
            usage_notes: &["include_hidden: list hidden joints as well"],
            sdk_refs: &["DzBone"],
        },
        CommandKnowledge {
            name: "set_joint_rotation",
            description: "Set a joint rotation",
            category: "Rigging",
            parameters: &["figure_id", "joint", "rotation", "space"],
            high_risk: false,
            usage_notes: &["rotation: [x, y, z] Euler angles", "space: local, world"],
            sdk_refs: &["DzBone"],
        },
        CommandKnowledge {
            name: "set_ik_fk_blend",
            description: "Set IK/FK blend on a limb",
            category: "Rigging",
            parameters: &["figure_id", "limb", "blend"],
            high_risk: false,
            usage_notes: &["limb: arm, leg, both", "blend: 0.0 (FK) to 1.0 (IK)"],
            sdk_refs: &["DzScript"],
        },
        CommandKnowledge {
            name: "add_joint",
            description: "Add a new joint to a figure",
            category: "Rigging",
            parameters: &["figure_id", "joint_name", "parent_joint", "position"],
            high_risk: true,
            usage_notes: &["Adds a custom joint to a figure skeleton"],
            sdk_refs: &["DzBone"],
        },
        // ── Transform Commands ──────────────────────────────────────────────────
        CommandKnowledge {
            name: "set_transform",
            description: "Set node transform (position/rotation/scale)",
            category: "Transform",
            parameters: &["node_id", "position", "rotation", "scale", "space"],
            high_risk: false,
            usage_notes: &["Set node position, rotation, and/or scale", "space: local, world"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "align_nodes",
            description: "Align nodes to a target node",
            category: "Transform",
            parameters: &["target_node", "node_ids", "axes", "alignment"],
            high_risk: false,
            usage_notes: &["axes: which axes to align (x, y, z, all)", "alignment: min, center, max"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "distribute_nodes",
            description: "Distribute nodes evenly along an axis",
            category: "Transform",
            parameters: &["node_ids", "axis", "spacing", "bounds"],
            high_risk: false,
            usage_notes: &["Spacing: fixed spacing or auto-even"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "snap_to_ground",
            description: "Snap a node to the ground or another node",
            category: "Transform",
            parameters: &["node_id", "offset_y", "snap_to_node"],
            high_risk: false,
            usage_notes: &["Snap node to ground plane or another node"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "reset_transform",
            description: "Reset node transform to defaults",
            category: "Transform",
            parameters: &["node_id", "position", "rotation", "scale"],
            high_risk: false,
            usage_notes: &["Reset selected transform components to defaults"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "set_pivot",
            description: "Set a node's pivot point",
            category: "Transform",
            parameters: &["node_id", "pivot"],
            high_risk: false,
            usage_notes: &["Set node pivot point for transforms"],
            sdk_refs: &["DzNode"],
        },
        // ── Scene Commands ──────────────────────────────────────────────────────
        CommandKnowledge {
            name: "set_visibility",
            description: "Show or hide a node",
            category: "Scene",
            parameters: &["node_id", "visible", "recursive"],
            high_risk: false,
            usage_notes: &["recursive: apply to all children"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "delete_nodes",
            description: "Delete multiple nodes from the scene",
            category: "Scene",
            parameters: &["node_ids"],
            high_risk: true,
            usage_notes: &["Delete multiple nodes at once"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "duplicate_nodes",
            description: "Duplicate one or more nodes",
            category: "Scene",
            parameters: &["node_ids", "copies", "offset"],
            high_risk: false,
            usage_notes: &["copies: number of copies", "offset: position offset per copy"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "rename_node",
            description: "Rename a scene node",
            category: "Scene",
            parameters: &["node_id", "new_name"],
            high_risk: false,
            usage_notes: &["Rename a scene node"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "group_nodes",
            description: "Group nodes under a new parent",
            category: "Scene",
            parameters: &["node_ids", "group_name"],
            high_risk: false,
            usage_notes: &["Group nodes under a new null parent"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "merge_scene",
            description: "Merge a scene file into the current scene",
            category: "Scene",
            parameters: &["filepath", "import_location"],
            high_risk: true,
            usage_notes: &["filepath: path to scene file to merge"],
            sdk_refs: &["DzScene"],
        },
        CommandKnowledge {
            name: "get_scene_stats",
            description: "Get scene statistics",
            category: "Scene",
            parameters: &["detailed"],
            high_risk: false,
            usage_notes: &["detailed: include per-node breakdown"],
            sdk_refs: &["DzScene"],
        },
        // ── Animation Commands ─────────────────────────────────────────────────
        CommandKnowledge {
            name: "bake_physics",
            description: "Bake physics simulation to keyframes",
            category: "Animation",
            parameters: &["node_id", "range_start", "range_end", "sample_rate"],
            high_risk: false,
            usage_notes: &["sample_rate: frames between samples"],
            sdk_refs: &["DzKeyframe"],
        },
        // ── Selection Map Commands ───────────────────────────────────────────────
        CommandKnowledge {
            name: "selection_map_list",
            description: "List selection set maps",
            category: "Selection",
            parameters: &[],
            high_risk: false,
            usage_notes: &["List all available selection maps (named selection sets)"],
            sdk_refs: &["DzSelectionMap"],
        },
        CommandKnowledge {
            name: "selection_map_get_pairs",
            description: "Get all node-group pairs in a selection map",
            category: "Selection",
            parameters: &["map_index"],
            high_risk: false,
            usage_notes: &["Retrieve all node-group pairs from a selection map by index"],
            sdk_refs: &["DzSelectionMap"],
        },
        CommandKnowledge {
            name: "selection_map_add_pair",
            description: "Add a node-group pair to a selection map",
            category: "Selection",
            parameters: &["map_index", "node_id", "group_name"],
            high_risk: false,
            usage_notes: &["Add a new node-group pair to a selection map"],
            sdk_refs: &["DzSelectionMap"],
        },
        CommandKnowledge {
            name: "selection_map_remove_pair",
            description: "Remove a node-group pair from a selection map by index",
            category: "Selection",
            parameters: &["map_index", "pair_index"],
            high_risk: false,
            usage_notes: &["Remove a node-group pair from a selection map by its index"],
            sdk_refs: &["DzSelectionMap"],
        },
        CommandKnowledge {
            name: "selection_map_clear",
            description: "Clear all pairs from a selection map",
            category: "Selection",
            parameters: &["map_index"],
            high_risk: false,
            usage_notes: &["Remove all pairs from a selection map"],
            sdk_refs: &["DzSelectionMap"],
        },
        // ── Node Control Commands ───────────────────────────────────────────────
        CommandKnowledge {
            name: "set_node_selectable",
            description: "Control whether a node can be selected in the viewport",
            category: "Node",
            parameters: &["node_id", "selectable"],
            high_risk: false,
            usage_notes: &["Set whether a node can be selected in the viewport"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "set_render_visible",
            description: "Control whether a node is visible in renders",
            category: "Node",
            parameters: &["node_id", "visible"],
            high_risk: false,
            usage_notes: &["Set whether a node is visible in rendered output"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "parent_node",
            description: "Reparent a node under a new parent",
            category: "Node",
            parameters: &["node_id", "parent_id"],
            high_risk: true,
            usage_notes: &["Reparent a node to a new parent in the scene hierarchy"],
            sdk_refs: &["DzNode"],
        },
        CommandKnowledge {
            name: "unparent_node",
            description: "Remove a node from its parent",
            category: "Node",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Unparent a node, making it a top-level node"],
            sdk_refs: &["DzNode"],
        },
        // ── Mesh Query Commands ─────────────────────────────────────────────────
        CommandKnowledge {
            name: "mesh_get_vertex_count",
            description: "Get vertex count of a mesh node",
            category: "Mesh",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Get the number of vertices in a mesh node"],
            sdk_refs: &["DzFacetMesh", "DzVertexMesh"],
        },
        CommandKnowledge {
            name: "mesh_get_face_count",
            description: "Get face/polygon count of a mesh node",
            category: "Mesh",
            parameters: &["node_id"],
            high_risk: false,
            usage_notes: &["Get the number of faces/polygons in a mesh node"],
            sdk_refs: &["DzFacetMesh", "DzVertexMesh"],
        },
        // ── Material Commands ───────────────────────────────────────────────────
        CommandKnowledge {
            name: "get_shape_materials",
            description: "List material names on a shape",
            category: "Material",
            parameters: &["node_id", "shape_index"],
            high_risk: false,
            usage_notes: &["List all material names assigned to a shape"],
            sdk_refs: &["DzShape", "DzMaterial"],
        },
        // ── Property Commands ───────────────────────────────────────────────────
        CommandKnowledge {
            name: "lock_property",
            description: "Lock or unlock a property",
            category: "Property",
            parameters: &["node_id", "property_name", "locked"],
            high_risk: false,
            usage_notes: &["Lock or unlock a property by name"],
            sdk_refs: &["DzProperty"],
        },
    ]
}

impl Default for CommandKnowledgeBase {
    fn default() -> Self {
        Self::new()
    }
}
